"""initial schema

Revision ID: 87b8c92203de
Revises: 
Create Date: 2026-08-20 22:00:41.535600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.models.base import GUID

# revision identifiers, used by Alembic.
revision: str = '87b8c92203de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user')),
    sa.UniqueConstraint('email', name=op.f('uq_app_user_email')),
    sa.UniqueConstraint('username', name=op.f('uq_app_user_username'))
    )
    op.create_table('school',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_school')),
    sa.UniqueConstraint('name', name=op.f('uq_school_name'))
    )
    op.create_table('course',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('school_id', GUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], name=op.f('fk_course_school_id_school'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course')),
    sa.UniqueConstraint('school_id', 'name', name=op.f('uq_course_school_id'))
    )
    op.create_table('refresh_token',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_refresh_token_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_token')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_token_token_hash'))
    )
    op.create_index('ix_refresh_token_family', 'refresh_token', ['family_id'], unique=False)
    op.create_index('ix_refresh_token_user', 'refresh_token', ['user_id'], unique=False)
    op.create_table('upload',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('source_type', sa.Enum('book', 'lecture', 'note', 'keypoint_list', 'past_paper', 'manual_text', 'extra_requirement', name='source_type'), nullable=False),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('storage_key', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('shareable', sa.Boolean(), nullable=False),
    sa.Column('parse_status', sa.Text(), nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(source_type IN ('manual_text', 'extra_requirement') AND raw_text IS NOT NULL) OR (source_type NOT IN ('manual_text', 'extra_requirement') AND storage_key IS NOT NULL)", name=op.f('ck_upload_payload_present')),
    sa.CheckConstraint("source_type NOT IN ('manual_text', 'extra_requirement') OR shareable = false", name=op.f('ck_upload_manual_not_shareable')),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_upload_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_upload'))
    )
    op.create_index('idx_upload_user', 'upload', ['user_id', 'created_at'], unique=False)
    op.create_table('job',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('school_id', GUID(), nullable=True),
    sa.Column('course_id', GUID(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('need_explanation', sa.Boolean(), nullable=False),
    sa.Column('enable_review', sa.Boolean(), nullable=False),
    sa.Column('planned_total', sa.Integer(), nullable=True),
    sa.Column('md_key', sa.Text(), nullable=True),
    sa.Column('pdf_key', sa.Text(), nullable=True),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_minutes BETWEEN 5 AND 300', name=op.f('ck_job_valid_duration')),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('fk_job_course_id_course')),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], name=op.f('fk_job_school_id_school')),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_job_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job'))
    )
    op.create_index('idx_job_user', 'job', ['user_id', 'created_at'], unique=False)
    op.create_table('resource',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('upload_id', GUID(), nullable=False),
    sa.Column('source_type', sa.Enum('book', 'lecture', 'note', 'keypoint_list', 'past_paper', 'manual_text', 'extra_requirement', name='source_type'), nullable=False),
    sa.Column('school_id', GUID(), nullable=True),
    sa.Column('course_id', GUID(), nullable=True),
    sa.Column('parsed_key', sa.Text(), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=True),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('is_shared = false OR (school_id IS NOT NULL AND course_id IS NOT NULL)', name=op.f('ck_resource_shared_needs_scope')),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('fk_resource_course_id_course')),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], name=op.f('fk_resource_school_id_school')),
    sa.ForeignKeyConstraint(['upload_id'], ['upload.id'], name=op.f('fk_resource_upload_id_upload'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource'))
    )
    op.create_index('idx_resource_shared_scope', 'resource', ['school_id', 'course_id', 'source_type'], unique=False, postgresql_where='is_shared = true')
    op.create_table('job_stage',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_id', GUID(), nullable=False),
    sa.Column('stage', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name=op.f('fk_job_stage_job_id_job'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_stage')),
    sa.UniqueConstraint('job_id', 'seq', name=op.f('uq_job_stage_job_id'))
    )
    op.create_index('idx_job_stage_job_seq', 'job_stage', ['job_id', 'seq'], unique=False)
    op.create_table('job_upload',
    sa.Column('job_id', GUID(), nullable=False),
    sa.Column('upload_id', GUID(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name=op.f('fk_job_upload_job_id_job'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_id'], ['upload.id'], name=op.f('fk_job_upload_upload_id_upload')),
    sa.PrimaryKeyConstraint('job_id', 'upload_id', name=op.f('pk_job_upload'))
    )
    op.create_table('llm_call',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_id', GUID(), nullable=False),
    sa.Column('agent_role', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name=op.f('fk_llm_call_job_id_job'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_call'))
    )
    op.create_index('idx_llm_call_job', 'llm_call', ['job_id'], unique=False)
    op.create_table('moderation_record',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('resource_id', GUID(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], name=op.f('fk_moderation_record_resource_id_resource'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_moderation_record'))
    )
    op.create_index('ix_moderation_resource', 'moderation_record', ['resource_id'], unique=False)
    op.create_table('plan_item',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('job_id', GUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.Text(), nullable=False),
    sa.Column('knowledge_point', sa.Text(), nullable=False),
    sa.Column('exam_direction', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Text(), nullable=False),
    sa.Column('reference_source', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('superseded_by', GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name=op.f('fk_plan_item_job_id_job'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superseded_by'], ['plan_item.id'], name=op.f('fk_plan_item_superseded_by_plan_item')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_item')),
    sa.UniqueConstraint('job_id', 'seq', name=op.f('uq_plan_item_job_id'))
    )
    op.create_table('question',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('job_id', GUID(), nullable=False),
    sa.Column('plan_item_id', GUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.Text(), nullable=False),
    sa.Column('stem', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('sub_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sub_answers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('replanned_from', GUID(), nullable=True),
    sa.Column('review_passed', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("question_type <> 'choice' OR options IS NOT NULL", name=op.f('ck_question_choice_has_options')),
    sa.CheckConstraint('(sub_questions IS NULL) = (sub_answers IS NULL)', name=op.f('ck_question_sub_pair')),
    sa.CheckConstraint('retry_count <= 3', name=op.f('ck_question_retry_bounded')),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name=op.f('fk_question_job_id_job'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_item_id'], ['plan_item.id'], name=op.f('fk_question_plan_item_id_plan_item')),
    sa.ForeignKeyConstraint(['replanned_from'], ['plan_item.id'], name=op.f('fk_question_replanned_from_plan_item')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question')),
    sa.UniqueConstraint('job_id', 'seq', name=op.f('uq_question_job_id'))
    )
    op.create_index('idx_question_job', 'question', ['job_id', 'seq'], unique=False)
    op.create_table('retry_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', GUID(), nullable=True),
    sa.Column('plan_item_id', GUID(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('counted', sa.Boolean(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['plan_item_id'], ['plan_item.id'], name=op.f('fk_retry_log_plan_item_id_plan_item')),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name=op.f('fk_retry_log_question_id_question'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retry_log'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retry_log')
    op.drop_index('idx_question_job', table_name='question')
    op.drop_table('question')
    op.drop_table('plan_item')
    op.drop_index('ix_moderation_resource', table_name='moderation_record')
    op.drop_table('moderation_record')
    op.drop_index('idx_llm_call_job', table_name='llm_call')
    op.drop_table('llm_call')
    op.drop_table('job_upload')
    op.drop_index('idx_job_stage_job_seq', table_name='job_stage')
    op.drop_table('job_stage')
    op.drop_index('idx_resource_shared_scope', table_name='resource', postgresql_where='is_shared = true')
    op.drop_table('resource')
    op.drop_index('idx_job_user', table_name='job')
    op.drop_table('job')
    op.drop_index('idx_upload_user', table_name='upload')
    op.drop_table('upload')
    op.drop_index('ix_refresh_token_user', table_name='refresh_token')
    op.drop_index('ix_refresh_token_family', table_name='refresh_token')
    op.drop_table('refresh_token')
    op.drop_table('course')
    op.drop_table('school')
    op.drop_table('app_user')
    # ### end Alembic commands ###
