"""add chunk table for vector storage

Revision ID: a1b2c3d4e5f6
Revises: 87b8c92203de
Create Date: 2026-08-23 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.config import settings
from app.models.base import GUID

# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '87b8c92203de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# pgvector 的 Vector 类型
try:
    from pgvector.sqlalchemy import Vector
except ImportError:
    Vector = None  # type: ignore


def upgrade() -> None:
    # 向量维度由环境变量 EMBEDDING_DIMENSIONS 决定（默认 1536），
    # 建库时读取当时环境的值；pgvector 列维度建后不可变，换嵌入模型
    # 需要新迁移重建 chunk 表。
    embedding_dim = settings.embedding_dimensions

    # 启用 pgvector 扩展
    conn = op.get_bind()
    conn.execute(sa.text('CREATE EXTENSION IF NOT EXISTS vector'))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunk',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('resource_id', GUID(), nullable=False),
    sa.Column('upload_id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('school_id', GUID(), nullable=True),
    sa.Column('course_id', GUID(), nullable=True),
    sa.Column('source_type', sa.Enum('book', 'lecture', 'note', 'keypoint_list', 'past_paper', 'manual_text', 'extra_requirement', name='source_type'), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(dim=embedding_dim), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('fk_chunk_course_id_course')),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], name=op.f('fk_chunk_resource_id_resource'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], name=op.f('fk_chunk_school_id_school')),
    sa.ForeignKeyConstraint(['upload_id'], ['upload.id'], name=op.f('fk_chunk_upload_id_upload')),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_chunk_user_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunk'))
    )
    op.create_index('idx_chunk_vector', 'chunk', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('idx_chunk_payload', 'chunk', ['school_id', 'course_id', 'source_type', 'is_shared'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chunk_payload', table_name='chunk')
    op.drop_index('idx_chunk_vector', 'chunk', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('chunk')
    # ### end Alembic commands ###
